pann: pann::NetCache Class Reference
pann::NetCache Class Reference
#include <Cache.h>
Public Types
typedef std::vector< NeuronIter > ThreadTaskType
typedef std::vector
< ThreadTaskType > FrontType
Public Member Functions
virtual void flush ()
virtual void printDebugInfo (std::ostringstream &ost) const
Public Attributes
std::vector< FrontType > data
Detailed Description
Definition at line 52 of file Cache.h.
Member Typedef Documentation
typedef std::vector<NeuronIter> pann::NetCache::ThreadTaskType
Definition at line 56 of file Cache.h.
typedef std::vector<ThreadTaskType> pann::NetCache::FrontType
Definition at line 57 of file Cache.h.
Member Function Documentation
virtual void pann::NetCache::flush () [inline, virtual]
Implements pann::Cache.
Definition at line 65 of file Cache.h.
References data, and pann::Cache::touch().
Referenced by pann::Net::load(), and pann::Net::regenerateCache().
virtual void pann::NetCache::printDebugInfo (std::ostringstream & ost) const [inline, virtual]
Implements pann::Cache.
Definition at line 73 of file Cache.h.
References data.
Referenced by pann::Net::printDebugInfo().
Member Data Documentation
std::vector<FrontType> pann::NetCache::data
Definition at line 61 of file Cache.h.
Referenced by GLWidget::calcCoords(), flush(), pann::Net::getOutput(), pann::Net::load(), printDebugInfo(), pann::Net::regenerateCache(), pann::Net::save(), and pann::Net::threadBase().
The documentation for this class was generated from the following file:
pann/trunk/src/Core/Cache.h