pann: pann::Cache Class Reference
pann::Cache Class Reference
#include <Cache.h>
Public Member Functions
Cache ()
virtual ~Cache ()
virtual void flush ()=0
void touch ()
void fixed ()
bool isOk () const
virtual void printDebugInfo (std::ostringstream &ost) const =0
Protected Attributes
bool coherent
Detailed Description
Abstract cache object In reality every class should inherit own SuperDuperCache from this class
Definition at line 19 of file Cache.h.
Constructor & Destructor Documentation
pann::Cache::Cache () [inline]
Definition at line 23 of file Cache.h.
virtual pann::Cache::~Cache () [inline, virtual]
Definition at line 24 of file Cache.h.
Member Function Documentation
virtual void pann::Cache::flush () [pure virtual]
Implemented in pann::NetCache.
void pann::Cache::touch () [inline]
Definition at line 28 of file Cache.h.
References coherent.
Referenced by pann::Net::addConnection(), pann::Net::addNeuron(), pann::Net::delConnection(), pann::Net::delNeuron(), pann::NetCache::flush(), pann::Net::setNeuronRole(), and pann::Net::setThreadCount().
void pann::Cache::fixed () [inline]
Definition at line 33 of file Cache.h.
References coherent.
Referenced by pann::Net::load(), and pann::Net::regenerateCache().
bool pann::Cache::isOk () const [inline]
Definition at line 38 of file Cache.h.
References coherent.
Referenced by pann::Net::getOutput(), and pann::Net::run().
virtual void pann::Cache::printDebugInfo (std::ostringstream & ost) const [pure virtual]
Implements pann::Object.
Implemented in pann::NetCache.
Member Data Documentation
bool pann::Cache::coherent [protected]
Definition at line 41 of file Cache.h.
Referenced by fixed(), isOk(), and touch().
The documentation for this class was generated from the following file:
pann/trunk/src/Core/Cache.h