pann: pann::ActivationFunction::TanH Class Reference
pann::ActivationFunction::TanH Class Reference
#include <ActivationFunction.h>
Public Member Functions
~TanH ()
virtual unsigned getId () const
virtual std::string getName () const
virtual Float f (Float _x) const
virtual Float derivative (Float) const
Static Public Member Functions
static Base * Instance ()
Static Public Attributes
static const Float a = 1.7159
static const Float b = 0.6667
Private Member Functions
TanH ()
Static Private Attributes
static Base * self = 0
Detailed Description
Hyperbolic tangent function id = 3 y = a*tanh(b*x)
Definition at line 128 of file ActivationFunction.h.
Constructor & Destructor Documentation
pann::ActivationFunction::TanH::TanH () [inline, private]
Definition at line 138 of file ActivationFunction.h.
Referenced by Instance().
pann::ActivationFunction::TanH::~TanH () [inline]
Definition at line 141 of file ActivationFunction.h.
Member Function Documentation
static Base* pann::ActivationFunction::TanH::Instance () [inline, static]
Reimplemented from pann::ActivationFunction::Base.
Definition at line 144 of file ActivationFunction.h.
References TanH().
Referenced by pann::ActivationFunction::getById().
virtual unsigned pann::ActivationFunction::TanH::getId () const [inline, virtual]
Implements pann::ActivationFunction::Base.
Definition at line 152 of file ActivationFunction.h.
virtual std::string pann::ActivationFunction::TanH::getName () const [inline, virtual]
Implements pann::ActivationFunction::Base.
Definition at line 153 of file ActivationFunction.h.
virtual Float pann::ActivationFunction::TanH::f (Float _x) const [inline, virtual]
Implements pann::ActivationFunction::Base.
Definition at line 155 of file ActivationFunction.h.
References a, and b.
virtual Float pann::ActivationFunction::TanH::derivative (Float) const [inline, virtual]
Implements pann::ActivationFunction::Base.
Definition at line 160 of file ActivationFunction.h.
Member Data Documentation
Base * pann::ActivationFunction::TanH::self = 0 [static, private]
Definition at line 131 of file ActivationFunction.h.
const Float pann::ActivationFunction::TanH::a = 1.7159 [static]
Definition at line 134 of file ActivationFunction.h.
Referenced by f().
const Float pann::ActivationFunction::TanH::b = 0.6667 [static]
Definition at line 135 of file ActivationFunction.h.
Referenced by f().
The documentation for this class was generated from the following files:
pann/trunk/src/Core/ActivationFunction.h
pann/trunk/src/Core/ActivationFunction.cpp