pann: pann::NetworkModel Namespace Reference
pann::NetworkModel Namespace Reference
Functions
Net * MultilayerPerceptron (vector< unsigned > layers, ActivationFunction::Base *af)
Net * MultilayerPerceptron (std::vector< unsigned > layers, ActivationFunction::Base *af)
Function Documentation
Net* pann::NetworkModel::MultilayerPerceptron (std::vector< unsigned > layers, ActivationFunction::Base * af)
Referenced by main().
Net* pann::NetworkModel::MultilayerPerceptron (vector< unsigned > layers, ActivationFunction::Base * af)
Definition at line 15 of file MultilayerPerceptron.cpp.
References pann::Net::addConnection(), pann::Net::addInputNeuron(), pann::Net::addNeuron(), pann::Net::getBiasId(), and pann::Net::setNeuronOwner().