from django.conf.urls.defaults import *

urlpatterns = patterns('',
    (r'face$', 'main.views.faces_list_all'),
    (r'dataset$', 'main.views.datasets_list_all'),
    (r'net$', 'main.views.nets_list_all'),
    (r'log$', 'main.views.logs_list_all'),
    (r'info$', 'main.views.info_list_all'),
    (r'info_graph$', 'main.views.info_get_graph'),
    (r'nets_actions',   'main.views.nets_actions'),
    (r'nets_rename',    'main.views.nets_rename'),
    (r'nets_showsize',  'main.views.nets_showsize'),
    (r'nets_load',      'main.views.nets_load'),
    (r'nets_save',      'main.views.nets_save'),
    (r'nets_reset',     'main.views.nets_reset'),
    (r'nets_delete',    'main.views.nets_delete'),
    (r'nets_copy',      'main.views.nets_copy'),
    (r'nets_test1',     'main.views.nets_test1'),
    (r'nets_test_set',  'main.views.nets_test_set'),
    (r'nets_train',     'main.views.nets_train'),
    (r'nets_create_mlp','main.views.nets_create_mlp'),
    (r'nets_create_gcnn','main.views.nets_create_gcnn'),
#    (r'html/(?P<path>.*)$', 'django.views.static.serve', {'document_root': '/home/booble/pann/trunk/src/Apps/hybrid/pann_web/main/html'}),

    (r'$', 'main.views.index'),
)
