# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.6

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canoncical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Produce verbose output by default.
VERBOSE = 1

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/booble/pann/trunk/src

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/booble/pann/trunk

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@echo "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@echo "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/booble/pann/trunk/CMakeFiles /home/booble/pann/trunk/CMakeFiles/progress.make
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/booble/pann/trunk/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named NeuronTest

# Build rule for target.
NeuronTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NeuronTest
.PHONY : NeuronTest

# fast build rule for target.
NeuronTest/fast:
	$(MAKE) -f CMakeFiles/NeuronTest.dir/build.make CMakeFiles/NeuronTest.dir/build
.PHONY : NeuronTest/fast

#=============================================================================
# Target rules for targets named ObjectTest

# Build rule for target.
ObjectTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ObjectTest
.PHONY : ObjectTest

# fast build rule for target.
ObjectTest/fast:
	$(MAKE) -f CMakeFiles/ObjectTest.dir/build.make CMakeFiles/ObjectTest.dir/build
.PHONY : ObjectTest/fast

#=============================================================================
# Target rules for targets named pann

# Build rule for target.
pann: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 pann
.PHONY : pann

# fast build rule for target.
pann/fast:
	$(MAKE) -f CMakeFiles/pann.dir/build.make CMakeFiles/pann.dir/build
.PHONY : pann/fast

Neuron.o: Neuron.cpp.o
.PHONY : Neuron.o

# target to build an object file
Neuron.cpp.o:
	$(MAKE) -f CMakeFiles/pann.dir/build.make CMakeFiles/pann.dir/Neuron.cpp.o
.PHONY : Neuron.cpp.o

Neuron.i: Neuron.cpp.i
.PHONY : Neuron.i

# target to preprocess a source file
Neuron.cpp.i:
	$(MAKE) -f CMakeFiles/pann.dir/build.make CMakeFiles/pann.dir/Neuron.cpp.i
.PHONY : Neuron.cpp.i

Neuron.s: Neuron.cpp.s
.PHONY : Neuron.s

# target to generate assembly for a file
Neuron.cpp.s:
	$(MAKE) -f CMakeFiles/pann.dir/build.make CMakeFiles/pann.dir/Neuron.cpp.s
.PHONY : Neuron.cpp.s

NeuronTest.o: NeuronTest.cpp.o
.PHONY : NeuronTest.o

# target to build an object file
NeuronTest.cpp.o:
	$(MAKE) -f CMakeFiles/NeuronTest.dir/build.make CMakeFiles/NeuronTest.dir/NeuronTest.cpp.o
.PHONY : NeuronTest.cpp.o

NeuronTest.i: NeuronTest.cpp.i
.PHONY : NeuronTest.i

# target to preprocess a source file
NeuronTest.cpp.i:
	$(MAKE) -f CMakeFiles/NeuronTest.dir/build.make CMakeFiles/NeuronTest.dir/NeuronTest.cpp.i
.PHONY : NeuronTest.cpp.i

NeuronTest.s: NeuronTest.cpp.s
.PHONY : NeuronTest.s

# target to generate assembly for a file
NeuronTest.cpp.s:
	$(MAKE) -f CMakeFiles/NeuronTest.dir/build.make CMakeFiles/NeuronTest.dir/NeuronTest.cpp.s
.PHONY : NeuronTest.cpp.s

Object.o: Object.cpp.o
.PHONY : Object.o

# target to build an object file
Object.cpp.o:
	$(MAKE) -f CMakeFiles/pann.dir/build.make CMakeFiles/pann.dir/Object.cpp.o
.PHONY : Object.cpp.o

Object.i: Object.cpp.i
.PHONY : Object.i

# target to preprocess a source file
Object.cpp.i:
	$(MAKE) -f CMakeFiles/pann.dir/build.make CMakeFiles/pann.dir/Object.cpp.i
.PHONY : Object.cpp.i

Object.s: Object.cpp.s
.PHONY : Object.s

# target to generate assembly for a file
Object.cpp.s:
	$(MAKE) -f CMakeFiles/pann.dir/build.make CMakeFiles/pann.dir/Object.cpp.s
.PHONY : Object.cpp.s

ObjectTest.o: ObjectTest.cpp.o
.PHONY : ObjectTest.o

# target to build an object file
ObjectTest.cpp.o:
	$(MAKE) -f CMakeFiles/ObjectTest.dir/build.make CMakeFiles/ObjectTest.dir/ObjectTest.cpp.o
.PHONY : ObjectTest.cpp.o

ObjectTest.i: ObjectTest.cpp.i
.PHONY : ObjectTest.i

# target to preprocess a source file
ObjectTest.cpp.i:
	$(MAKE) -f CMakeFiles/ObjectTest.dir/build.make CMakeFiles/ObjectTest.dir/ObjectTest.cpp.i
.PHONY : ObjectTest.cpp.i

ObjectTest.s: ObjectTest.cpp.s
.PHONY : ObjectTest.s

# target to generate assembly for a file
ObjectTest.cpp.s:
	$(MAKE) -f CMakeFiles/ObjectTest.dir/build.make CMakeFiles/ObjectTest.dir/ObjectTest.cpp.s
.PHONY : ObjectTest.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... NeuronTest"
	@echo "... ObjectTest"
	@echo "... edit_cache"
	@echo "... pann"
	@echo "... rebuild_cache"
	@echo "... Neuron.o"
	@echo "... Neuron.i"
	@echo "... Neuron.s"
	@echo "... NeuronTest.o"
	@echo "... NeuronTest.i"
	@echo "... NeuronTest.s"
	@echo "... Object.o"
	@echo "... Object.i"
	@echo "... Object.s"
	@echo "... ObjectTest.o"
	@echo "... ObjectTest.i"
	@echo "... ObjectTest.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

