pann: pann::ActivationFunction::Base Class Reference
pann::ActivationFunction::Base Class Reference
#include <ActivationFunction.h>
Public Member Functions
virtual unsigned getId () const =0
virtual std::string getName () const =0
virtual Float f (Float) const =0
virtual Float derivative (Float) const =0
Static Public Member Functions
static Base * Instance ()
Detailed Description
All activation functions inherit ActivationFunction::Base and implement Instance() method Base is a singleton pattern
Definition at line 22 of file ActivationFunction.h.
Member Function Documentation
static Base* pann::ActivationFunction::Base::Instance () [static]
Reimplemented in pann::ActivationFunction::Linear, pann::ActivationFunction::Threshold, and pann::ActivationFunction::TanH.
virtual unsigned pann::ActivationFunction::Base::getId () const [pure virtual]
Implemented in pann::ActivationFunction::Linear, pann::ActivationFunction::Threshold, and pann::ActivationFunction::TanH.
Referenced by pann::Neuron::printDebugInfo(), pann::Neuron::save(), and GLWidget::setInfoNeuron().
virtual std::string pann::ActivationFunction::Base::getName () const [pure virtual]
Implemented in pann::ActivationFunction::Linear, pann::ActivationFunction::Threshold, and pann::ActivationFunction::TanH.
Referenced by GLWidget::setInfoNeuron().
virtual Float pann::ActivationFunction::Base::f (Float) const [pure virtual]
Implemented in pann::ActivationFunction::Linear, pann::ActivationFunction::Threshold, and pann::ActivationFunction::TanH.
virtual Float pann::ActivationFunction::Base::derivative (Float) const [pure virtual]
Implemented in pann::ActivationFunction::Linear, pann::ActivationFunction::Threshold, and pann::ActivationFunction::TanH.
The documentation for this class was generated from the following file:
pann/trunk/src/Core/ActivationFunction.h