pann: pann::ActivationFunction Namespace Reference
pann::ActivationFunction Namespace Reference
Classes
class Base
class Linear
class Threshold
class TanH
Functions
Base * getById (const unsigned id)
Function Documentation
Base * pann::ActivationFunction::getById (const unsigned id)
Definition at line 21 of file ActivationFunction.cpp.
References pann::ActivationFunction::TanH::Instance(), pann::ActivationFunction::Threshold::Instance(), and pann::ActivationFunction::Linear::Instance().