pann: pann::FeedforwardPropagationRunner Class Reference
pann::FeedforwardPropagationRunner Class Reference
#include <Runner.h>
Public Member Functions
~FeedforwardPropagationRunner ()
virtual void run (Neuron *_neuron)
virtual RunDirection getDirection ()
Static Public Member Functions
static Runner * Instance ()
Private Member Functions
FeedforwardPropagationRunner ()
Static Private Attributes
static Runner * self = 0
Detailed Description
Definition at line 59 of file Runner.h.
Constructor & Destructor Documentation
pann::FeedforwardPropagationRunner::FeedforwardPropagationRunner () [private]
Definition at line 72 of file Runner.cpp.
Referenced by Instance().
pann::FeedforwardPropagationRunner::~FeedforwardPropagationRunner ()
Definition at line 76 of file Runner.cpp.
Member Function Documentation
Runner * pann::FeedforwardPropagationRunner::Instance () [static]
Reimplemented from pann::Runner.
Definition at line 81 of file Runner.cpp.
References FeedforwardPropagationRunner().
void pann::FeedforwardPropagationRunner::run (Neuron * _neuron) [virtual]
Implements pann::Runner.
Definition at line 90 of file Runner.cpp.
References pann::Neuron::activationValue, pann::ActivationFunction::Base::f(), pann::Neuron::getActivationFunction(), pann::Link::getDirection(), pann::Link::getTo(), pann::Link::getWeight(), pann::Link::in, pann::Neuron::links, pann::Neuron::receptiveField, and pann::Weight::value.
RunDirection pann::FeedforwardPropagationRunner::getDirection () [virtual]
Implements pann::Runner.
Definition at line 103 of file Runner.cpp.
References pann::ForwardRun.
Member Data Documentation
Runner * pann::FeedforwardPropagationRunner::self = 0 [static, private]
Definition at line 62 of file Runner.h.
The documentation for this class was generated from the following files:
pann/trunk/src/pann/Core/Runner.h
pann/trunk/src/pann/Core/Runner.cpp