pann: pann::Link Class Reference
pann::Link Class Reference
Link between two neurons.
#include <Link.h>
Public Types
enum Direction { in, out }
Public Member Functions
Link (Neuron *_to, const Direction _direction, Weight *_w, unsigned const _latency=1) throw ()
virtual ~Link () throw ()
Neuron * getTo () throw ()
const Neuron * getTo () const throw ()
Direction getDirection () const throw ()
unsigned getLatency () const throw ()
Weight * getWeight () throw ()
Private Member Functions
Link ()
template<class Archive>
void serialize (Archive &ar, const unsigned int version)
Private Attributes
Neuron * to
Direction direction
Weight * w
Pointer to Weight object (might be shared between different links).
unsigned latency
Friends
class boost::serialization::access
Detailed Description
Link between two neurons.
Definition at line 18 of file Link.h.
Member Enumeration Documentation
enum pann::Link::Direction
Enumerator:
in
out
Definition at line 22 of file Link.h.
Constructor & Destructor Documentation
pann::Link::Link (Neuron * _to, const Direction _direction, Weight * _w, unsigned const _latency = 1) throw ()
Definition at line 7 of file Link.cpp.
pann::Link::~Link () throw () [virtual]
Definition at line 15 of file Link.cpp.
pann::Link::Link () [inline, private]
Definition at line 45 of file Link.h.
Member Function Documentation
Neuron * pann::Link::getTo () throw ()
Definition at line 20 of file Link.cpp.
References to.
Referenced by pann::Net::regenerateCache(), and pann::FeedforwardPropagationRunner::run().
const Neuron * pann::Link::getTo () const throw ()
Definition at line 26 of file Link.cpp.
References to.
Link::Direction pann::Link::getDirection () const throw ()
Definition at line 32 of file Link.cpp.
References direction.
Referenced by pann::Net::regenerateCache(), and pann::FeedforwardPropagationRunner::run().
unsigned pann::Link::getLatency () const throw ()
Definition at line 37 of file Link.cpp.
References latency.
Referenced by pann::Net::regenerateCache().
Weight * pann::Link::getWeight () throw ()
Definition at line 43 of file Link.cpp.
References w.
Referenced by pann::FeedforwardPropagationRunner::run().
template<class Archive> void pann::Link::serialize (Archive & ar, const unsigned int version) [inline, private]
Reimplemented from pann::Object.
Definition at line 50 of file Link.h.
References direction, latency, to, and w.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Reimplemented from pann::Object.
Definition at line 45 of file Link.h.
Member Data Documentation
Neuron* pann::Link::to [private]
Definition at line 26 of file Link.h.
Referenced by getTo(), and serialize().
Direction pann::Link::direction [private]
Definition at line 27 of file Link.h.
Referenced by getDirection(), and serialize().
Weight* pann::Link::w [private]
Pointer to Weight object (might be shared between different links).
Definition at line 28 of file Link.h.
Referenced by getWeight(), and serialize().
unsigned pann::Link::latency [private]
Definition at line 29 of file Link.h.
Referenced by getLatency(), and serialize().
The documentation for this class was generated from the following files:
pann/trunk/src/pann/Core/Link.h
pann/trunk/src/pann/Core/Link.cpp