#ifndef PANN_ACTIVATIONFUNCTIONS_ALL_H_INCLUDED
#define PANN_ACTIVATIONFUNCTIONS_ALL_H_INCLUDED

#include "Linear.h"
#include "TanH.h"
#include "Threshold.h"

#endif //PANN_ACTIVATIONFUNCTIONS_ALL_H_INCLUDED

