
from Null import null
from FeedforwardPropagation import feedforward_propagation
from RandomizeWeightsGauss import randomize_weights_gauss
from RandomizeWeightsAccordingToInputsCount import randomize_weights_according_to_inputs_count

