pann: pann::Net Class Reference
pann::Net Class Reference
#include <Net.h>
Public Types
enum NeuronRole { WorkNeuron = 0, InputNeuron = 1 }
Public Member Functions
Net ()
Net (unsigned _threads)
~Net ()
unsigned getThreadCount () const
void setThreadCount (unsigned _threads)
unsigned addNeuron (ActivationFunction::Base *_activationFunction)
unsigned addInputNeuron ()
void delNeuron (unsigned _neuronId)
void setNeuronRole (unsigned _neuronId, NeuronRole _newRole)
NeuronRole getNeuronRole (unsigned _neuronId) const
void addConnection (unsigned _from, unsigned _to, Float _weightValue=1)
void delConnection (unsigned _from, unsigned _to)
void setNeuronOwner (unsigned _neuron, unsigned _owner)
unsigned getNeuronOwner (unsigned _neuron) const
std::vector< unsigned > getInputMap () const
void setInput (const std::valarray< Float > &_input)
std::map< unsigned, Float > getOutput () const
void getOutput (std::valarray< Float > &_output) const
void run (Runner *_runner)
const NetCache & getCache () const
const std::map< unsigned,
Neuron > & getNeurons () const
const std::map< unsigned,
Weight > & getWeights () const
unsigned getBiasId () const
void printDebugInfo (std::ostringstream &ost) const
Public Attributes
LearningHint::Base * learningHint
Private Member Functions
NeuronIter findNeuron (unsigned _neuronId)
ConstNeuronIter findNeuron (unsigned _neuronId) const
void formatFront (std::vector< NeuronIter > &_raw) const
void regenerateCache () const
template<class Archive>
void save (Archive &ar, const unsigned int version) const
template<class Archive>
void load (Archive &ar, const unsigned int version)
Static Private Member Functions
static void threadBase (Runner *_runner, NetCache *_cache, unsigned _cur_thread_no, boost::barrier *_barrier)
Private Attributes
unsigned threadCount
unsigned lastNeuronId
unsigned lastWeightId
unsigned biasId
std::map< unsigned, Neuron > neurons
std::map< unsigned, Weight > weights
std::list< NeuronIter > inputNeurons
NetCache cache
Friends
class boost::serialization::access
Detailed Description
Definition at line 17 of file Net.h.
Member Enumeration Documentation
enum pann::Net::NeuronRole
Enumerator:
WorkNeuron
InputNeuron
Definition at line 21 of file Net.h.
Constructor & Destructor Documentation
pann::Net::Net ()
Default constructor. Creates empty net and sets threadCount to hardware specific number (depends on available processors) Although creates bias neuron
Definition at line 9 of file Net.cpp.
pann::Net::Net (unsigned _threads)
Same as above, but threadCount is set to
Parameters:
_threads
Definition at line 14 of file Net.cpp.
References addConnection(), addNeuron(), biasId, pann::ActivationFunction::Linear::Instance(), lastNeuronId, lastWeightId, learningHint, and setThreadCount().
pann::Net::~Net ()
Definition at line 24 of file Net.cpp.
References learningHint.
Member Function Documentation
unsigned pann::Net::getThreadCount () const
Manipulate threadCount
Definition at line 31 of file Net.cpp.
References threadCount.
Referenced by GLWidget::setInfoNet().
void pann::Net::setThreadCount (unsigned _threads)
Definition at line 37 of file Net.cpp.
References cache, threadCount, and pann::Cache::touch().
Referenced by main(), and Net().
unsigned pann::Net::addNeuron (ActivationFunction::Base * _activationFunction)
Manipulate neurons in network Remark: addInputNeuron adds neuron with ActivationFunction::Linear
Definition at line 54 of file Net.cpp.
References cache, lastNeuronId, neurons, and pann::Cache::touch().
Referenced by addInputNeuron(), pann::NetworkModel::MultilayerPerceptron(), and Net().
unsigned pann::Net::addInputNeuron ()
Definition at line 67 of file Net.cpp.
References addNeuron(), InputNeuron, pann::ActivationFunction::Linear::Instance(), and setNeuronRole().
Referenced by pann::NetworkModel::MultilayerPerceptron().
void pann::Net::delNeuron (unsigned _neuronId)
Definition at line 76 of file Net.cpp.
References cache, delConnection(), findNeuron(), pann::Link::in, neurons, and pann::Cache::touch().
void pann::Net::setNeuronRole (unsigned _neuronId, NeuronRole _newRole)
Can turn work neuron to be input and vice versa
Definition at line 105 of file Net.cpp.
References cache, findNeuron(), InputNeuron, inputNeurons, pann::Cache::touch(), and WorkNeuron.
Referenced by addInputNeuron().
Net::NeuronRole pann::Net::getNeuronRole (unsigned _neuronId) const
Definition at line 127 of file Net.cpp.
References findNeuron(), and inputNeurons.
Referenced by GLWidget::calcCoords().
void pann::Net::addConnection (unsigned _from, unsigned _to, Float _weightValue = 1)
Manage connections between neurons TODO: add shared connections for convolution networks
Definition at line 144 of file Net.cpp.
References cache, findNeuron(), pann::Link::in, lastWeightId, pann::Link::out, pann::Cache::touch(), and weights.
Referenced by pann::NetworkModel::MultilayerPerceptron(), and Net().
void pann::Net::delConnection (unsigned _from, unsigned _to)
Definition at line 162 of file Net.cpp.
References cache, findNeuron(), pann::Link::in, pann::Link::out, pann::Cache::touch(), and weights.
Referenced by delNeuron().
void pann::Net::setNeuronOwner (unsigned _neuron, unsigned _owner)
Manage neuron owner thread It is usually much higher then threadCount
Definition at line 199 of file Net.cpp.
References findNeuron().
Referenced by pann::NetworkModel::MultilayerPerceptron().
unsigned pann::Net::getNeuronOwner (unsigned _neuron) const
Definition at line 205 of file Net.cpp.
References findNeuron().
std::vector< unsigned > pann::Net::getInputMap () const
Return IDs of input neurons (use it in case you don't "remember" what neurons are input or their order)
Definition at line 211 of file Net.cpp.
References inputNeurons.
void pann::Net::setInput (const std::valarray< Float > & _input)
Add values to input neurons receptive fields
Referenced by main().
map< unsigned, Float > pann::Net::getOutput () const
Returns pairs<input_neuron_id, it's output> (only for neurons in last cache layer)
Definition at line 238 of file Net.cpp.
References cache, pann::NetCache::data, pann::Cache::isOk(), and regenerateCache().
Referenced by main().
void pann::Net::getOutput (std::valarray< Float > & _output) const
Assign neurons outputs to specified by
Parameters:
_output valarray (it is slower then above version, but more useful)
void pann::Net::run (Runner * _runner)
Apply
Parameters:
_runner Runner to each neuron, layer by layer Note: layers are computed automaticaly and stored in cache See regenerateCache() implementation for more details
Definition at line 267 of file Net.cpp.
References cache, pann::Cache::isOk(), regenerateCache(), threadBase(), and threadCount.
Referenced by main().
const NetCache & pann::Net::getCache () const
Public interface to private attributes (they are used while training or painting net in pann_viewer)
Definition at line 283 of file Net.cpp.
References cache.
Referenced by GLWidget::calcCoords().
const map< unsigned, Neuron > & pann::Net::getNeurons () const
Definition at line 289 of file Net.cpp.
References neurons.
Referenced by GLWidget::drawNetModel(), GLWidget::setInfoNet(), and GLWidget::setInfoNeuron().
const map< unsigned, Weight > & pann::Net::getWeights () const
Definition at line 295 of file Net.cpp.
References weights.
Referenced by GLWidget::setInfoNet().
unsigned pann::Net::getBiasId () const
Get ID of bias neuron Remark: bias neuron is implemented as work neuron, with self-recurrent connection (w=1), placed at first cache layer
Definition at line 301 of file Net.cpp.
References biasId.
Referenced by GLWidget::drawNetModel(), and pann::NetworkModel::MultilayerPerceptron().
NeuronIter pann::Net::findNeuron (unsigned _neuronId) [private]
Returns NeuronIterator for corresponding neuron ID
Definition at line 307 of file Net.cpp.
References neurons.
Referenced by addConnection(), delConnection(), delNeuron(), findNeuron(), getNeuronOwner(), getNeuronRole(), regenerateCache(), setNeuronOwner(), and setNeuronRole().
ConstNeuronIter pann::Net::findNeuron (unsigned _neuronId) const [private]
Definition at line 317 of file Net.cpp.
References findNeuron().
void pann::Net::formatFront (std::vector< NeuronIter > & _raw) const [private]
Helper used by regenerateCache()
Referenced by regenerateCache().
void pann::Net::regenerateCache () const [private]
This function updates cache Be extremely careful!
Definition at line 340 of file Net.cpp.
References biasId, cache, pann::NetCache::data, findNeuron(), pann::Cache::fixed(), pann::NetCache::flush(), formatFront(), pann::Link::getDirection(), pann::Link::getLatency(), pann::Link::getToIter(), pann::Link::in, and inputNeurons.
Referenced by getOutput(), and run().
static void pann::Net::threadBase (Runner * _runner, NetCache * _cache, unsigned _cur_thread_no, boost::barrier * _barrier) [inline, static, private]
This function is executed by work thread, instantiated from run()
Definition at line 158 of file Net.h.
References pann::BackwardRun, pann::NetCache::data, pann::ForwardRun, pann::Runner::getDirection(), and pann::Runner::run().
Referenced by run().
void pann::Net::printDebugInfo (std::ostringstream & ost) const [inline, virtual]
Implements pann::Object.
Definition at line 189 of file Net.h.
References cache, inputNeurons, lastNeuronId, lastWeightId, neurons, pann::NetCache::printDebugInfo(), threadCount, and weights.
template<class Archive> void pann::Net::save (Archive & ar, const unsigned int version) const [inline, private]
Definition at line 220 of file Net.h.
References biasId, cache, pann::NetCache::data, pann::Link::getDirection(), pann::Link::getLatency(), pann::Link::getToIter(), pann::LearningHint::Base::getTypeId(), pann::Link::getWeightIter(), inputNeurons, lastNeuronId, lastWeightId, learningHint, neurons, threadCount, and weights.
template<class Archive> void pann::Net::load (Archive & ar, const unsigned int version) [inline, private]
Definition at line 300 of file Net.h.
References biasId, cache, pann::NetCache::data, pann::Cache::fixed(), pann::NetCache::flush(), pann::LearningHint::getById(), pann::Object::id, inputNeurons, lastNeuronId, lastWeightId, learningHint, neurons, threadCount, and weights.
Friends And Related Function Documentation
friend class boost::serialization::access [friend]
Reimplemented from pann::Object.
Definition at line 214 of file Net.h.
Member Data Documentation
LearningHint::Base* pann::Net::learningHint
Definition at line 123 of file Net.h.
Referenced by pann::LMS::init(), load(), Net(), save(), pann::LMS::train(), and ~Net().
unsigned pann::Net::threadCount [private]
Definition at line 127 of file Net.h.
Referenced by getThreadCount(), load(), printDebugInfo(), run(), save(), and setThreadCount().
unsigned pann::Net::lastNeuronId [private]
Definition at line 128 of file Net.h.
Referenced by addNeuron(), load(), Net(), printDebugInfo(), and save().
unsigned pann::Net::lastWeightId [private]
Definition at line 129 of file Net.h.
Referenced by addConnection(), load(), Net(), printDebugInfo(), and save().
unsigned pann::Net::biasId [private]
Definition at line 130 of file Net.h.
Referenced by getBiasId(), load(), Net(), regenerateCache(), and save().
std::map<unsigned, Neuron> pann::Net::neurons [private]
Definition at line 131 of file Net.h.
Referenced by addNeuron(), delNeuron(), findNeuron(), getNeurons(), load(), printDebugInfo(), and save().
std::map<unsigned, Weight> pann::Net::weights [private]
Definition at line 132 of file Net.h.
Referenced by addConnection(), delConnection(), getWeights(), load(), printDebugInfo(), and save().
std::list<NeuronIter> pann::Net::inputNeurons [private]
Definition at line 133 of file Net.h.
Referenced by getInputMap(), getNeuronRole(), load(), printDebugInfo(), regenerateCache(), save(), and setNeuronRole().
NetCache pann::Net::cache [mutable, private]
Definition at line 134 of file Net.h.
Referenced by addConnection(), addNeuron(), delConnection(), delNeuron(), getCache(), getOutput(), load(), printDebugInfo(), regenerateCache(), run(), save(), setNeuronRole(), and setThreadCount().
The documentation for this class was generated from the following files:
pann/trunk/src/Core/Net.h
pann/trunk/src/Core/Net.cpp