pann: pann/trunk/src/UnitTests/TestNet.cpp File Reference
pann/trunk/src/UnitTests/TestNet.cpp File Reference
#include <iostream>
#include <iomanip>
#include "Includes.h"
#include "Type.h"
#include "Net.h"
#include "Storage.h"
#include "NetworkModel.h"
#include "TrainData.h"
Functions
int main ()
Function Documentation
int main (void)
Definition at line 17 of file TestNet.cpp.
References pann::Net::getOutput(), pann::TrainPattern::input, pann::NetworkModel::MultilayerPerceptron(), pann::Net::run(), pann::Net::setInput(), and pann::Net::setThreadCount().