pann: pann::ActivationFunction::Threshold Class Reference
pann::ActivationFunction::Threshold Class Reference
#include <ActivationFunction.h>
Public Member Functions
~Threshold ()
virtual unsigned getId () const
virtual std::string getName () const
virtual Float f (Float _x) const
virtual Float derivative (Float _x) const
Static Public Member Functions
static Base * Instance ()
Private Member Functions
Threshold ()
Static Private Attributes
static Base * self = 0
Detailed Description
MacCalloc-Pitz threshold function id = 2 y = 0, x <0 y = 1, x>=0
Definition at line 85 of file ActivationFunction.h.
Constructor & Destructor Documentation
pann::ActivationFunction::Threshold::Threshold () [inline, private]
Definition at line 91 of file ActivationFunction.h.
Referenced by Instance().
pann::ActivationFunction::Threshold::~Threshold () [inline]
Definition at line 94 of file ActivationFunction.h.
Member Function Documentation
static Base* pann::ActivationFunction::Threshold::Instance () [inline, static]
Reimplemented from pann::ActivationFunction::Base.
Definition at line 97 of file ActivationFunction.h.
References Threshold().
Referenced by pann::ActivationFunction::getById().
virtual unsigned pann::ActivationFunction::Threshold::getId () const [inline, virtual]
Implements pann::ActivationFunction::Base.
Definition at line 105 of file ActivationFunction.h.
virtual std::string pann::ActivationFunction::Threshold::getName () const [inline, virtual]
Implements pann::ActivationFunction::Base.
Definition at line 106 of file ActivationFunction.h.
virtual Float pann::ActivationFunction::Threshold::f (Float _x) const [inline, virtual]
Implements pann::ActivationFunction::Base.
Definition at line 108 of file ActivationFunction.h.
virtual Float pann::ActivationFunction::Threshold::derivative (Float _x) const [inline, virtual]
Implements pann::ActivationFunction::Base.
Definition at line 115 of file ActivationFunction.h.
References pann::inf.
Member Data Documentation
Base * pann::ActivationFunction::Threshold::self = 0 [static, private]
Definition at line 88 of file ActivationFunction.h.
The documentation for this class was generated from the following files:
pann/trunk/src/Core/ActivationFunction.h
pann/trunk/src/Core/ActivationFunction.cpp