pann: pann::ActivationFunction::Linear Class Reference
pann::ActivationFunction::Linear Class Reference
#include <ActivationFunction.h>
Public Member Functions
~Linear ()
virtual unsigned getId () const
virtual std::string getName () const
virtual Float f (Float _x) const
virtual Float derivative (Float) const
Static Public Member Functions
static Base * Instance ()
Private Member Functions
Linear ()
Static Private Attributes
static Base * self = 0
Detailed Description
Linear function id = 1 y = x dy/dx = 0
Definition at line 42 of file ActivationFunction.h.
Constructor & Destructor Documentation
pann::ActivationFunction::Linear::Linear () [inline, private]
Definition at line 48 of file ActivationFunction.h.
Referenced by Instance().
pann::ActivationFunction::Linear::~Linear () [inline]
Definition at line 51 of file ActivationFunction.h.
Member Function Documentation
static Base* pann::ActivationFunction::Linear::Instance () [inline, static]
Reimplemented from pann::ActivationFunction::Base.
Definition at line 57 of file ActivationFunction.h.
References Linear().
Referenced by pann::Net::addInputNeuron(), pann::ActivationFunction::getById(), and pann::Net::Net().
virtual unsigned pann::ActivationFunction::Linear::getId () const [inline, virtual]
Implements pann::ActivationFunction::Base.
Definition at line 65 of file ActivationFunction.h.
virtual std::string pann::ActivationFunction::Linear::getName () const [inline, virtual]
Implements pann::ActivationFunction::Base.
Definition at line 66 of file ActivationFunction.h.
virtual Float pann::ActivationFunction::Linear::f (Float _x) const [inline, virtual]
Implements pann::ActivationFunction::Base.
Definition at line 68 of file ActivationFunction.h.
virtual Float pann::ActivationFunction::Linear::derivative (Float) const [inline, virtual]
Implements pann::ActivationFunction::Base.
Definition at line 73 of file ActivationFunction.h.
Member Data Documentation
Base * pann::ActivationFunction::Linear::self = 0 [static, private]
Definition at line 45 of file ActivationFunction.h.
The documentation for this class was generated from the following files:
pann/trunk/src/Core/ActivationFunction.h
pann/trunk/src/Core/ActivationFunction.cpp