pann: GLWidget Class Reference
GLWidget Class Reference
#include <glwidget.h>
Public Slots
void setXRotation (int angle)
void setYRotation (int angle)
void setZRotation (int angle)
void setScale (float)
void setTranslation (float, float, float)
void restoreDefaults ()
Public Member Functions
GLWidget (pann::Net *_net, QLabel *_label, QWidget *parent=0)
~GLWidget ()
Protected Member Functions
void initializeGL ()
void paintGL ()
void resizeGL (int width, int height)
void mousePressEvent (QMouseEvent *event)
void mouseMoveEvent (QMouseEvent *event)
void keyPressEvent (QKeyEvent *e)
void wheelEvent (QWheelEvent *e)
Private Member Functions
void calcCoords ()
void setInfoNeuron (unsigned)
void setInfoNet ()
void normalizeAngle (int *angle)
void drawNetModel ()
Private Attributes
pann::Net * p_net
QLabel * info_label
std::map
< pann::ConstNeuronIter,
Coords,
pann::NeuronIterCompare > coords
int xRot
int yRot
int zRot
QPoint lastPos
float scale
float xTrans
float yTrans
float zTrans
bool drawBiasLinks
bool drawLinks
float neuronRadius
unsigned linkRate
Classes
struct Coords
Detailed Description
Definition at line 12 of file glwidget.h.
Constructor & Destructor Documentation
GLWidget::GLWidget (pann::Net * _net, QLabel * _label, QWidget * parent = 0)
Definition at line 10 of file glwidget.cpp.
References calcCoords(), drawNetModel(), restoreDefaults(), and setInfoNet().
GLWidget::~GLWidget ()
Definition at line 22 of file glwidget.cpp.
Member Function Documentation
void GLWidget::setXRotation (int angle) [slot]
Definition at line 194 of file glwidget.cpp.
References normalizeAngle(), and xRot.
Referenced by keyPressEvent(), mouseMoveEvent(), and restoreDefaults().
void GLWidget::setYRotation (int angle) [slot]
Definition at line 203 of file glwidget.cpp.
References normalizeAngle(), and yRot.
Referenced by keyPressEvent(), mouseMoveEvent(), and restoreDefaults().
void GLWidget::setZRotation (int angle) [slot]
Definition at line 212 of file glwidget.cpp.
References normalizeAngle(), and zRot.
Referenced by mouseMoveEvent(), and restoreDefaults().
void GLWidget::setScale (float _scale) [slot]
Definition at line 221 of file glwidget.cpp.
References scale.
Referenced by keyPressEvent(), restoreDefaults(), and wheelEvent().
void GLWidget::setTranslation (float _x, float _y, float _z) [slot]
Definition at line 230 of file glwidget.cpp.
References xTrans, yTrans, and zTrans.
Referenced by keyPressEvent(), mouseMoveEvent(), and restoreDefaults().
void GLWidget::restoreDefaults () [slot]
Definition at line 241 of file glwidget.cpp.
References drawBiasLinks, drawLinks, linkRate, neuronRadius, setScale(), setTranslation(), setXRotation(), setYRotation(), and setZRotation().
Referenced by GLWidget(), and keyPressEvent().
void GLWidget::initializeGL () [protected]
Definition at line 257 of file glwidget.cpp.
void GLWidget::paintGL () [protected]
Definition at line 301 of file glwidget.cpp.
References scale, xRot, xTrans, yRot, yTrans, zRot, and zTrans.
void GLWidget::resizeGL (int width, int height) [protected]
Definition at line 313 of file glwidget.cpp.
void GLWidget::mousePressEvent (QMouseEvent * event) [protected]
Definition at line 323 of file glwidget.cpp.
References lastPos.
void GLWidget::mouseMoveEvent (QMouseEvent * event) [protected]
Definition at line 328 of file glwidget.cpp.
References lastPos, setTranslation(), setXRotation(), setYRotation(), setZRotation(), xRot, xTrans, yRot, yTrans, zRot, and zTrans.
void GLWidget::keyPressEvent (QKeyEvent * e) [protected]
Definition at line 345 of file glwidget.cpp.
References restoreDefaults(), scale, setScale(), setTranslation(), setXRotation(), setYRotation(), xRot, xTrans, yRot, yTrans, and zTrans.
void GLWidget::wheelEvent (QWheelEvent * e) [protected]
Definition at line 392 of file glwidget.cpp.
References scale, and setScale().
void GLWidget::calcCoords () [private]
Definition at line 27 of file glwidget.cpp.
References pann::Color::b, pann::OpenGLHint::color, GLWidget::Coords::color, coords, pann::NetCache::data, pann::Color::g, pann::Net::getCache(), pann::Net::getNeuronRole(), p_net, pann::OpenGLHint::point, pann::Color::r, GLWidget::Coords::x, pann::Point3d::x, GLWidget::Coords::y, pann::Point3d::y, GLWidget::Coords::z, and pann::Point3d::z.
Referenced by GLWidget().
void GLWidget::setInfoNeuron (unsigned _id) [private]
Definition at line 140 of file glwidget.cpp.
References pann::Neuron::activationValue, pann::Neuron::getActivationFunction(), pann::ActivationFunction::Base::getId(), pann::ActivationFunction::Base::getName(), pann::Net::getNeurons(), pann::Neuron::getOwnerThread(), info_label, pann::Neuron::links, p_net, and pann::Neuron::receptiveField.
void GLWidget::setInfoNet () [private]
Definition at line 157 of file glwidget.cpp.
References drawBiasLinks, drawLinks, pann::Net::getNeurons(), pann::Net::getThreadCount(), pann::Net::getWeights(), info_label, linkRate, and p_net.
Referenced by GLWidget().
void GLWidget::normalizeAngle (int * angle) [private]
Definition at line 186 of file glwidget.cpp.
Referenced by setXRotation(), setYRotation(), and setZRotation().
void GLWidget::drawNetModel () [private]
Definition at line 89 of file glwidget.cpp.
References GLWidget::Coords::color, coords, drawBiasLinks, drawLinks, pann::Net::getBiasId(), pann::Net::getNeurons(), linkRate, neuronRadius, p_net, GLWidget::Coords::x, GLWidget::Coords::y, and GLWidget::Coords::z.
Referenced by GLWidget().
Member Data Documentation
pann::Net* GLWidget::p_net [private]
Definition at line 38 of file glwidget.h.
Referenced by calcCoords(), drawNetModel(), setInfoNet(), and setInfoNeuron().
QLabel* GLWidget::info_label [private]
Definition at line 39 of file glwidget.h.
Referenced by setInfoNet(), and setInfoNeuron().
std::map<pann::ConstNeuronIter, Coords, pann::NeuronIterCompare> GLWidget::coords [private]
Definition at line 48 of file glwidget.h.
Referenced by calcCoords(), and drawNetModel().
int GLWidget::xRot [private]
Definition at line 61 of file glwidget.h.
Referenced by keyPressEvent(), mouseMoveEvent(), paintGL(), and setXRotation().
int GLWidget::yRot [private]
Definition at line 62 of file glwidget.h.
Referenced by keyPressEvent(), mouseMoveEvent(), paintGL(), and setYRotation().
int GLWidget::zRot [private]
Definition at line 63 of file glwidget.h.
Referenced by mouseMoveEvent(), paintGL(), and setZRotation().
QPoint GLWidget::lastPos [private]
Definition at line 64 of file glwidget.h.
Referenced by mouseMoveEvent(), and mousePressEvent().
float GLWidget::scale [private]
Definition at line 67 of file glwidget.h.
Referenced by keyPressEvent(), paintGL(), setScale(), and wheelEvent().
float GLWidget::xTrans [private]
Definition at line 70 of file glwidget.h.
Referenced by keyPressEvent(), mouseMoveEvent(), paintGL(), and setTranslation().
float GLWidget::yTrans [private]
Definition at line 71 of file glwidget.h.
Referenced by keyPressEvent(), mouseMoveEvent(), paintGL(), and setTranslation().
float GLWidget::zTrans [private]
Definition at line 72 of file glwidget.h.
Referenced by keyPressEvent(), mouseMoveEvent(), paintGL(), and setTranslation().
bool GLWidget::drawBiasLinks [private]
Definition at line 75 of file glwidget.h.
Referenced by drawNetModel(), restoreDefaults(), and setInfoNet().
bool GLWidget::drawLinks [private]
Definition at line 76 of file glwidget.h.
Referenced by drawNetModel(), restoreDefaults(), and setInfoNet().
float GLWidget::neuronRadius [private]
Definition at line 77 of file glwidget.h.
Referenced by drawNetModel(), and restoreDefaults().
unsigned GLWidget::linkRate [private]
Definition at line 78 of file glwidget.h.
Referenced by drawNetModel(), restoreDefaults(), and setInfoNet().
The documentation for this class was generated from the following files:
pann/trunk/src/Utils/pann_viewer/glwidget.h
pann/trunk/src/Utils/pann_viewer/glwidget.cpp